version: "3.9"

services:
  frontend:
    tty: true
    build:
      context: .
      dockerfile: ./client/Dockerfile
    depends_on:
      - backend
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - "8080:8080"

  backend:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DB_URI=mongodb://db/e-market
    volumes:
      - ./server:/app
      - /app/node_modules
    command: npm run dev

  db:
    image: mongo:4.2.7
    ports:
      - "27017:27017"
