version: "3.9"

services:
  app:
    image: tahsinature/vue-store:latest
    container_name: vue-store
    environment:
      DOPPLER_TOKEN: $DOPPLER_TOKEN_MY_PERSONAL
      DOPPLER_PROJECT: vue-store
      DOPPLER_CONFIG: prd
    labels:
      - traefik.enable=true
      - traefik.http.routers.vue-store.rule=Host(`vue-store.tahsin.us`)
      - traefik.http.routers.vue-store.entrypoints=websecure
      - traefik.http.services.vue-store.loadbalancer.server.port=3000
      - traefik.http.routers.vue-store.tls=true
      - traefik.http.routers.vue-store.tls.certresolver=myresolver
    entrypoint: sh -c './scripts/get-env && npm start'
    networks:
      - traefik

networks:
  traefik:
    external: true
